import type { ThreatIntelEntry } from "./types";

export const INITIAL_THREAT_INTEL: ThreatIntelEntry[] = [
  // High reputation (most dangerous)
  {
    id: "ti-1",
    ip: "185.220.101.42",
    reputation: "high",
    category: "Tor Exit Node",
    country: "Germany",
    lastSeen: "2026-04-04",
    attackCount: 847,
    tags: ["tor", "anonymizer", "high-volume"],
  },
  {
    id: "ti-2",
    ip: "45.33.32.156",
    reputation: "high",
    category: "C2 Server",
    country: "USA",
    lastSeen: "2026-04-05",
    attackCount: 1243,
    tags: ["c2", "botnet", "malware"],
  },
  {
    id: "ti-3",
    ip: "192.42.116.16",
    reputation: "high",
    category: "Botnet Node",
    country: "Netherlands",
    lastSeen: "2026-04-05",
    attackCount: 523,
    tags: ["botnet", "ddos"],
  },
  {
    id: "ti-4",
    domain: "evil-malware.xyz",
    reputation: "high",
    category: "Malware Distribution",
    country: "Russia",
    lastSeen: "2026-04-03",
    attackCount: 334,
    tags: ["malware", "phishing"],
  },
  {
    id: "ti-5",
    ip: "103.21.58.42",
    reputation: "high",
    category: "SQLi Source",
    country: "India",
    lastSeen: "2026-04-05",
    attackCount: 78,
    tags: ["sqli", "scanner"],
  },
  {
    id: "ti-6",
    ip: "91.219.29.81",
    reputation: "high",
    category: "Ransomware C2",
    country: "Ukraine",
    lastSeen: "2026-04-04",
    attackCount: 412,
    tags: ["ransomware", "c2"],
  },
  {
    id: "ti-7",
    domain: "phishing-bank.tk",
    reputation: "high",
    category: "Phishing",
    country: "Nigeria",
    lastSeen: "2026-04-02",
    attackCount: 156,
    tags: ["phishing", "credential-theft"],
  },
  // Medium reputation
  {
    id: "ti-8",
    ip: "194.165.16.11",
    reputation: "medium",
    category: "Port Scanner",
    country: "France",
    lastSeen: "2026-04-01",
    attackCount: 89,
    tags: ["scanner", "recon"],
  },
  {
    id: "ti-9",
    ip: "78.142.23.101",
    reputation: "medium",
    category: "Brute Force",
    country: "Poland",
    lastSeen: "2026-03-30",
    attackCount: 234,
    tags: ["brute-force", "auth"],
  },
  {
    id: "ti-10",
    domain: "suspicious-api.info",
    reputation: "medium",
    category: "API Abuse",
    country: "China",
    lastSeen: "2026-04-01",
    attackCount: 67,
    tags: ["api", "scraper"],
  },
  {
    id: "ti-11",
    ip: "109.238.2.99",
    reputation: "medium",
    category: "Proxy Node",
    country: "Bulgaria",
    lastSeen: "2026-03-28",
    attackCount: 45,
    tags: ["proxy", "anonymizer"],
  },
  {
    id: "ti-12",
    ip: "5.188.206.14",
    reputation: "medium",
    category: "XSS Source",
    country: "Russia",
    lastSeen: "2026-04-03",
    attackCount: 112,
    tags: ["xss", "injection"],
  },
  {
    id: "ti-13",
    domain: "free-vpn-proxy.net",
    reputation: "medium",
    category: "VPN/Proxy",
    country: "UK",
    lastSeen: "2026-03-25",
    attackCount: 23,
    tags: ["vpn", "proxy"],
  },
  {
    id: "ti-14",
    ip: "203.0.113.47",
    reputation: "medium",
    category: "DDoS Node",
    country: "Brazil",
    lastSeen: "2026-04-02",
    attackCount: 167,
    tags: ["ddos", "amplification"],
  },
  // Low reputation
  {
    id: "ti-15",
    ip: "198.51.100.33",
    reputation: "low",
    category: "Known Scanner",
    country: "Sweden",
    lastSeen: "2026-03-20",
    attackCount: 12,
    tags: ["scanner"],
  },
  {
    id: "ti-16",
    ip: "192.0.2.88",
    reputation: "low",
    category: "Research IP",
    country: "USA",
    lastSeen: "2026-03-15",
    attackCount: 5,
    tags: ["research", "benign"],
  },
  {
    id: "ti-17",
    domain: "security-test.io",
    reputation: "low",
    category: "Pentest Tool",
    country: "UK",
    lastSeen: "2026-03-10",
    attackCount: 8,
    tags: ["pentest", "security"],
  },
  {
    id: "ti-18",
    ip: "172.16.0.55",
    reputation: "low",
    category: "Internal Scanner",
    country: "India",
    lastSeen: "2026-03-18",
    attackCount: 3,
    tags: ["internal", "scan"],
  },
  {
    id: "ti-19",
    ip: "10.0.0.254",
    reputation: "low",
    category: "Dev Environment",
    country: "India",
    lastSeen: "2026-03-22",
    attackCount: 7,
    tags: ["dev", "testing"],
  },
  {
    id: "ti-20",
    domain: "bugbounty-research.com",
    reputation: "low",
    category: "Bug Bounty",
    country: "USA",
    lastSeen: "2026-03-25",
    attackCount: 15,
    tags: ["bug-bounty", "research"],
  },
  {
    id: "ti-21",
    ip: "45.142.212.100",
    reputation: "high",
    category: "Credential Stuffer",
    country: "Russia",
    lastSeen: "2026-04-05",
    attackCount: 892,
    tags: ["credential-stuffing", "automation"],
  },
  {
    id: "ti-22",
    ip: "162.247.74.201",
    reputation: "high",
    category: "Tor Exit Node",
    country: "USA",
    lastSeen: "2026-04-04",
    attackCount: 445,
    tags: ["tor", "anonymizer"],
  },
  {
    id: "ti-23",
    ip: "185.107.47.215",
    reputation: "medium",
    category: "MITM Proxy",
    country: "Germany",
    lastSeen: "2026-04-01",
    attackCount: 78,
    tags: ["mitm", "proxy"],
  },
  {
    id: "ti-24",
    domain: "malicious-cdn.ru",
    reputation: "high",
    category: "Malware CDN",
    country: "Russia",
    lastSeen: "2026-04-05",
    attackCount: 1567,
    tags: ["malware", "cdn", "c2"],
  },
  {
    id: "ti-25",
    ip: "77.88.55.242",
    reputation: "medium",
    category: "DNS Poisoner",
    country: "Russia",
    lastSeen: "2026-03-29",
    attackCount: 56,
    tags: ["dns", "spoofing"],
  },
];
